services:
  database:
    image: postgres:18
    container_name: fintrac-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fintrac
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintrac"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fintrac-backend
    ports:
      - "5134:5134"
    environment:
      ConnectionString: "Host=database;Port=5432;Username=postgres;Password=postgres;Database=fintrac;"
      JWTKey: 1e2d5686470c4a9db9fa9bb82a8a33672dd7c1de64bb9d836a1fa9a54d095c0a
      JWTIssuer: FinTrac
      JWTAudience: FinTrac
      FrontendAddress: http://localhost:5173
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: fintrac-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5134
    depends_on:
      - backend

